
version: '2.1'
services:
  gutendex_app:
    build: .
    container_name: gutendex_app
    networks:
      - gutendex_net
    ports:
      - 8000:8000
    depends_on:
      gutendex:
        condition: service_healthy 
    links:
      - gutendex:gutendex

  gutendex:
    image: postgres:14.5
    container_name: gutendex
    networks:
      - gutendex_net
    ports:
      - 5432:5432
    volumes:
      - ./db/init_user_db.sh:/docker-entrypoint-initdb.d/init_user_db.sh
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U gutendex -d gutendex"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: gutendex
      POSTGRES_DB: gutendex


networks:
  gutendex_net:
    name: gutendex_net

volumes:
  db_data:
    name: db_data